firstRun=false
currversion=1.1.1
raw_dataset=/mnt/Data/Practice/PhD_projects/low_input_project/raw_data
result_pipeline=/mnt/Data/Practice/PhD_projects/low_input_project/test_pipeline
genome_ref=/mnt/Data/Practice/reference_genome/arabidopsis/genome
genome_name=Arabidopsis_thaliana.TAIR10.dna.toplevel.fa
genome_type=Arabidopsis
docker_mode=false
parallel_mode=true
npar=4
fastq_path=/home/linuxbrew/.linuxbrew/bin/fastqc
number_of_dataset=2
dataset_size=8.9
pairs_mode=true
first_pattern=_1.fq.gz
secnd_pattern=_2.fq.gz
java_path=/home/linuxbrew/.linuxbrew/bin/java
trim_path=/usr/local/bin/Trimmomatic-0.39/dist/jar
trim_jar=/usr/local/bin/Trimmomatic-0.39/dist/jar/trimmomatic-0.39.jar
dir_adap=$trim_path
name_adap=/usr/local/bin/Trimmomatic-0.39/dist/jar/TruSeq3-PE-2.fa
xGen_adap=/usr/local/bin/Trimmomatic-0.39/dist/jar/xgen_overrep_adapters.fa
end_mode=PE
ill_clip=1:30:9
LEADING=20
TRAILING=20
SLIDINGWINDOW=4:20
MINLEN=36
n_th=8
tg_2colour=33
tg_poly_g=true
tg_poly_a=true
tg_length=36
tg_clip_R1=16
tg_clip_R2=16
tg_three_prime_clip_R1=16
tg_three_prime_clip_R2=16
fastp_qualified_quality_phred=20
fastp_trim_front1=10
fastp_trim_tail1=0
fastp_trim_front2=10
fastp_trim_tail2=0
fastp_length_required=30
fastp_trim_poly_g=true
fastp_detect_adapter_for_pe=true
bismark_path=/home/bia-ubuntu/bin/Bismark-0.24.2
samtools_path=/home/linuxbrew/.linuxbrew/bin/samtools
bedtools_path=/home/linuxbrew/.linuxbrew/bin/bedtools
modified_time=1779239694
bis_parallel=8
buf_size=40
Nthreads=4
nucleotide=true
intermediate_files=false
run_pair_bismark=false
bismark_mapping_mode=PE
deduplicate=-p
methextractor=-p
del_inter_file=true
single_cell=true
directional=--non_directional
quickrun=0
st_prep=0
st_trim=2
st_fastq=2
st_bismark=0
st_bissort=0
st_coreport=0
st_fastqbam=2
st_bisdedup=0
st_dedsort=0
st_bismeth=2
st_cx=0
st_methimpute=0
st_dmrcaller=0
st_bigwig=0
st_bedgraph=0
st_methykit=0
intermediate=true
intermediate_mode=constrained
fit_output=false
enrichment_plot=false
full_report=false
context_report=All
mincov=1
file=0
NCORES=4
resultdir=true
genomref=true
email_sen=methylstar@johannes.org
email_rec=notifymailbinhvo@gmail.com
password=bplcpyrwbnxolsab
active=true
tmp_rdata=$result_pipeline/rdata
tmp_fq=$result_pipeline/trimming-files
tmp_log=$result_pipeline/trimming-logs
tmp_qcfast=$result_pipeline/qc-fastq-reports
tmp_bismap=$result_pipeline/bismark-mappers
tmp_covseq=$result_pipeline/cov-seq-reports
tmp_qcbam=$result_pipeline/qc-bam-reports
tmp_dide=$result_pipeline/bismark-deduplicate
tmp_dme=$result_pipeline/bismark-meth-extractor
tmp_clog=$result_pipeline/logs
tmp_cx_report=$result_pipeline/cx-reports
tmp_meth_out=$result_pipeline/methimpute-out
tmp_tes_out=$result_pipeline/tes-reports
tmp_gen_out=$result_pipeline/gene-reports
tmp_fit_out=$result_pipeline/fit-reports
tmp_methyl_fmt=$result_pipeline/methylkit-format
tmp_dmr=$result_pipeline/dmrcaller-format
tmp_bed=$result_pipeline/bedgraph-format
tmp_bigwig=$result_pipeline/bigwig-format
